spring:
  profiles:
    active: postgres
  application:
    name: InAllMedia

  # Configuração comum
  jpa:
    hibernate:
      ddl-auto: update

  # GraphQL
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

# Documentação da API
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Configuração do servidor
server:
  port: 8080

---
# Perfil PostgreSQL (produção)
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/inallmedia
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

---
# Perfil H2 (desenvolvimento/testes)
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:inallmedia
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console